//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public Nullable<int> TenantSender { get; set; }
        public Nullable<int> TenantReceiver { get; set; }
        public Nullable<int> ManagerSender { get; set; }
        public Nullable<int> ManagerReceiver { get; set; }
        public string Message1 { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual PropertyManager PropertyManager { get; set; }
        public virtual PropertyManager PropertyManager1 { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual Tenant Tenant1 { get; set; }
    }
}
