//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PropertyProjectManagerEntities : DbContext
    {
        public PropertyProjectManagerEntities()
            : base("name=PropertyProjectManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Leas> Leases { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PropertyManager> PropertyManagers { get; set; }
        public virtual DbSet<PropertyOwner> PropertyOwners { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
    }
}
